<?php
$CONFIGNL = array (
  'newsLetter'  => 'Instituto Deandhela Newsletter Semanal',
  'tituloCabelaho' => 'Estratégias para aumentar sua produtividade!',
  'corCabecalho' => 'b44772',
  'mascoteImage' => 'https://raw.githubusercontent.com/jpblbastos/images/master/mascote-id.png',
  'quantidadePost' => 3,
  'post1' => 
  array (
    'tituloPost' => 'Seja um Mestre',
    'iconePost'  => 'https://raw.githubusercontent.com/jpblbastos/images/master/remote_work.png',
    'textoPost'  => 'É preciso muito treino para tornar-se um mestre.',
    'botaoPost'  => 'Ative seu Jedi',
    'linkPost'   => 'http://institutodeandhela.com.br/blog/treino-para-tornar-se-um-mestre/'
  ),
  'post2' => 
  array (
    'tituloPost' => 'Chega de Reunião Improdutivas',
    'iconePost'  => 'https://raw.githubusercontent.com/jpblbastos/images/master/4_power_ups2.png',
    'textoPost'  => 'As reuniões na minha empresa são improdutivas. E agora?',
    'botaoPost'  => 'Fique Ligado!',
    'linkPost'   => 'http://institutodeandhela.com.br/blog/reunioes-improdutivas/'
  ),
  'post3' => 
  array (
    'tituloPost' => 'Helio viado',
    'iconePost'  => 'https://raw.githubusercontent.com/jpblbastos/images/master/remote_work.png',
    'textoPost'  => 'descubra aqui pq o heluio e viado.',
    'botaoPost'  => 'Ative seu Jedi',
    'linkPost'   => 'http://institutodeandhela.com.br/blog/treino-para-tornar-se-um-mestre/'
  ),
  'tituloRodape' => '[Infográfico] Razões para treinar sua equipe:',
  'conteudoRodape' => 'Montamos um guia completo para dominar o treinamento da sua equipe \o/',
  'botaoRodape' => 'Baixe o Guia',
  'linkRodape' => 'http://conteudo.institutodeandhela.com.br/razoes-treinar-equipe',
);
?>